name: sample_application
description: A new Flutter project.
publish_to: "none"
version: 1.2.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.2.1
  google_fonts: ^6.3.2

  cupertino_icons: ^1.0.2
  hms_room_kit:
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
