name: hms_room_kit
description: 100ms Room Kit provides simple & easy to use UI components to build Live Streaming & Video Conferencing experiences in your apps.
version: 1.2.0
homepage: https://www.100ms.live/
repository: https://github.com/100mslive/100ms-flutter
issue_tracker: https://github.com/100mslive/100ms-flutter/issues
documentation: https://www.100ms.live/docs

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  hmssdk_flutter: 1.11.0
  intl: ^0.20.2
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  google_fonts: ^6.3.2
  draggable_widget: ^2.0.0
  badges: ^3.1.2
  shared_preferences: ^2.5.3
  lottie: ^3.3.2
  flutter_svg: ^2.2.1
  path_provider: ^2.1.5
  dropdown_button2: ^2.3.9
  focus_detector_v2: ^3.1.0+1
  flutter_linkify: ^6.0.0
  tuple: ^2.0.2
  url_launcher: ^6.3.2
  share_plus: ^12.0.1
  collection: ^1.19.1
  dots_indicator: ^4.0.1
  webview_flutter: ^4.13.0
  pointer_interceptor: ^0.10.1+2
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0

flutter:
  assets:
    - lib/src/assets/
    - lib/src/assets/icons/
